name: Build mjai-reviewer for Windows

on:
  push:
    branches: [ "master" ]  # 可以根据你的需求调整触发分支
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        profile: minimal
        override: true
      
    - name: Build mjai-reviewer
      run: |
        cd ..
        git clone https://github.com/Equim-chan/mjai-reviewer.git
        cd mjai-reviewer
        cargo build --release
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mjai-reviewer
        path: D:\a\mjai-reviewer\mjai-reviewer\target\release\mjai-reviewer.exe
